### ISSUE TITLE
Exception in classifier evaluation

### ISSUE THREAD

**Issue by jpivarski** [rinnert/pytorch-brief-intro#1]
I don't know if you'd be notified of the comment, but you'll definitely get this: the commit that needs to be reverted is bdbea62434285af48ee54c7c2639a1075995853d.

Anyway, great presentation. Thank you!

**Comment by rinnert** [comment]
Thank you for your kind words!  I enjoyed the interested audience and the good questions.

I fixed the exception shortly after the presentation.  I tested again on Binder and it is all fine now.
